services:
  java:
    build: .
    ports:
      - "1234:8080"

    depends_on:
      - mysql


  mysql:

    image: mysql:8.0
    environment:
      MYSQL_DATABASE: businessproject
      MYSQL_PASSWORD: root
      MYSQL_USERNAME: root
      MYSQL_ROOT_PASSWORD: root

    ports:
      - "3306:3306"



